export const CLICKED_ELEM = 'CLICKED_ELEM';
export const UNCLICKED_ELEM = 'UNCLICKED_ELEM';
export const DISABLED='DISABLED';
export const REQUEST_ELEMENTS_PENDING = 'REQUEST_ELEMENTS_PENDING';
export const REQUEST_ELEMENTS_SUCCESS = 'REQUEST_ELEMENTS_SUCCESS';
export const REQUEST_ELEMENTS_FAILED = 'REQUEST_ELEMENTS_FAILED';
export const REQUEST_ALL_SUCCESS = 'REQUEST_ALL_SUCCESS';
